# Generated by Django 6.0.3 on 2026-04-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_at_purchase",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price at purchase"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["-date"], name="idx_order_recent"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="idx_orderitem_ord_prd"
            ),
        ),
    ]
