# Generated by Django 6.0.3 on 2026-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="idx_product_name"),
        ),
    ]
